- .vscode/settings.json
- packages/lms-common/src/fileName.ts
- packages/lms-common/src/index.ts
Adds supporting file for lms import command
Tied to this PR: https://github.com/lmstudio-ai/lms/pull/23
> Adds lms import command

- README.md
- publish/sdk/README.md
Added some example output for the methods to help devs see at a glance what it looks like
Also changed the example to one that I got working pretty consistently
> Add output examples to Readme

- packages/lms-client/src/llm/LLMDynamicHandle.ts
- packages/lms-client/src/modelShared/ModelNamespace.ts
- packages/lms-common/src/LazySignal.ts
- packages/lms-common/src/index.ts
- packages/lms-external-backend-interfaces/src/llmBackendInterface.ts
Also adds countTokens endpoint.
> Adds async derive to LazySignal.

- packages/lms-client/src/index.ts
- packages/lms-client/src/repository/ModelSearchResultDownloadOption.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
Depends on https://github.com/lmstudio-ai/lms/pull/90
> Improve lms get

- packages/lms-kv-config/src/schema.ts
These configs are now in shared
> Remove onnx specific KVs that are already in shared config

- packages/lms-client/src/repository/RepositoryNamespace.ts
- packages/lms-es-plugin-runner/src/EsPluginInstaller.ts
- packages/lms-es-plugin-runner/src/esbuildArgs.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
- publish/sdk/package.json
Depends on https://github.com/lmstudio-ai/lms/pull/109
> Fix issues and bring in lms-cli

- packages/lms-communication-client/src/WsClientTransport.ts
- scaffolds/node-javascript/src/index.js
- scaffolds/node-typescript/src/index.ts
- Fixes authentication errors not displayed
- Fixed errors in the scaffolds
- Also brings in lms-cli fix that https://github.com/lmstudio-ai/lms/pull/119
depends on https://github.com/lmstudio-ai/lms/pull/119
> Fix errors not displayed. Also fix errors in the template

- packages/lms-common-server/src/findLMStudioHome.ts
- packages/lms-common-server/src/index.ts
- packages/lms-es-plugin-runner/package.json
- packages/lms-es-plugin-runner/src/UtilBinary.ts
- packages/lms-lmstudio/package.json
- packages/lms-lmstudio/src/installCli/index.ts
- publish/sdk/README.md
Depends on https://github.com/lmstudio-ai/lms/pull/124
Not ready to merge until LM Studio is ready.
> Remove dot cache assumption

- package-lock.json
- package.json
One of parcel's dependency lmdb fails to build on certain platforms. We remove parcel since we no longer depend on it.
> Removes dependency on parcel

- packages/lms-shared-types/src/ArtifactManifest.ts
- packages/lms-shared-types/src/ArtifactManifestBase.ts
- packages/lms-shared-types/src/PluginManifest.ts
- packages/lms-shared-types/src/PresetManifest.ts
- packages/lms-shared-types/src/index.ts
Allow the artifact type to be "preset".
> Add the preset artifact type

- packages/lms-client/src/plugins/processing/ProcessingController.ts
- packages/lms-shared-types/src/index.ts
- packages/lms-shared-types/src/llm/ContentBlockStyle.ts
- packages/lms-shared-types/src/llm/processing/GeneratorUpdate.ts
- packages/lms-shared-types/src/llm/processing/ProcessingUpdate.ts
Allows us to update thinking blocks.
> Thinking blocks status updates

- package-lock.json
- packages/lms-common/package.json
- packages/lms-isomorphic/src/browser/WebSocket.ts
We did not have boxen as our dependency but we do depend on it.
> Add missed dependency

- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
Adds top-k sampling support for MLX as described here https://github.com/lmstudio-ai/mlx-engine/issues/59
> [MLX] Add top-k sampling support

- packages/lms-client/src/modelShared/ModelNamespace.ts
- packages/lms-external-backend-interfaces/src/baseModelBackendInterface.ts
- release.sh
Waiting on https://github.com/lmstudio-ai/lms/pull/143
> Add TTL and improve safety of the release script

- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
Reverts lmstudio-ai/lmstudio.js#183
Causes https://discord.com/channels/1110598183144399058/1333091790412058754
> Revert "[MLX] Add top-k sampling support"

- packages/lms-kv-config/src/KVConfig.ts
- packages/lms-kv-config/src/schema.ts
- packages/lms-kv-config/src/valueTypes.ts
- packages/lms-shared-types/src/KVConfig.ts
- packages/lms-shared-types/src/index.ts
> Speculative decoding and field dependencies

- packages/lms-client/src/llm/LLMDynamicHandle.ts
- packages/lms-external-backend-interfaces/src/llmBackendInterface.ts
- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
- packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
Adds a method to preload a draft model. Also adds the remaining fields for speculative decoding.
> Preload draft model

- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
- packages/lms-kv-config/src/valueTypes.ts
- packages/lms-shared-types/src/index.ts
- packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
Group the two fields into one field.
> Rework types for reasoning parsing

- packages/lms-client/src/llm/LLMDynamicHandle.ts
Fix passing in structured generation with raw JSON Schema. This fixes the conversation naming.
> Fix structured field getting wiped

- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
- packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
More precisely represents what this parameter does
> Rename minAcceptProb for spec decoding

- packages/lms-external-backend-interfaces/src/llmBackendInterface.ts
> Add toolCallGenerationFailed event

- packages/lms-kv-config/src/conversion/llmPredictionConfig.ts
- packages/lms-kv-config/src/schema.ts
- packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
All
- draftModel
llama.cpp
- minDraftLengthToConsider
- numReuseTokens
- minContinueDraftingProbability
mlx
- numDraftTokensExact
Also updates llama.cpp defaults to match https://github.com/ggml-org/llama.cpp/commit/abd4d0bc4f1a9a0e429bc8ee0d5ece2a394a0a39
> Proper spec decoding param organization

- packages/lms-client/src/llm/.test-snapshots/LLM.complete.heavy.test.ts.snap
- packages/lms-client/src/llm/.test-snapshots/LLM.respond.heavy.test.ts.snap
- packages/lms-client/src/llm/LLM.complete.heavy.test.ts
- packages/lms-client/src/llm/LLM.heavy.test.ts
- packages/lms-client/src/llm/LLM.respond.heavy.test.ts
- packages/lms-client/src/modelShared/ModelNamespace.ts
- packages/lms-client/src/shared.heavy.test.ts
Tests for structured generation, speculative decoding, properties.
> Third wave of tests

- packages/lms-client/src/index.ts
- packages/lms-client/src/llm/ActResult.ts
- packages/lms-client/src/llm/LLMDynamicHandle.ts
- publish/sdk/src/exportedTypes.ts
Also renames totalOperationTimeSeconds to totalExecutionTimeSeconds.
> Rename OperationResult to ActResult.

- packages/lms-common/src/.test-snapshots/SlicedSignal.test.ts.snap
- packages/lms-common/src/SlicedSignal.test.ts
- packages/lms-common/src/SlicedSignal.ts
Allow slice signal to work with maps.
> Add support for maps with slice signals

- package.json
- packages/lms-client/src/system/SystemNamespace.ts
- packages/lms-external-backend-interfaces/src/systemBackendInterface.ts
Requires lms PR: https://github.com/lmstudio-ai/lms/pull/193
> Allow settings and view experiment flags

- packages/lms-communication-client/src/WsClientTransport.ts
Fixes https://github.com/lmstudio-ai/lmstudio-js/issues/149
> Fix references error on error

- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
- packages/lms-shared-types/src/ArtifactManifestBase.ts
- packages/lms-shared-types/src/index.ts
Depends on https://github.com/lmstudio-ai/lms/pull/209
> Allow artifact names to have dots

- packages/lms-client/src/repository/ArtifactDownloadPlanner.ts
- packages/lms-client/src/repository/ModelSearchResultDownloadOption.ts
- packages/lms-client/src/repository/RepositoryNamespace.ts
- packages/lms-common/src/Cleaner.ts
- packages/lms-common/src/LazySignal.ts
- packages/lms-common/src/Subscribable.ts
- packages/lms-communication/src/BackendInterface.ts
- packages/lms-communication/src/Channel.ts
- packages/lms-communication/src/index.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
- packages/lms-shared-types/src/ArtifactManifest.ts
- packages/lms-shared-types/src/index.ts
- packages/lms-shared-types/src/repository/ArtifactDownloadPlan.ts
Requires https://github.com/lmstudio-ai/lms/pull/213
> Add required interfaces and methods to let `lms get` download artifacts

- packages/lms-client/src/repository/RepositoryNamespace.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
- packages/lms-shared-types/src/index.ts
- packages/lms-shared-types/src/repository/ArtifactUpload.ts
Requires: https://github.com/lmstudio-ai/lms/pull/216
> lms push show file list

- packages/lms-client/src/plugins/processing/ProcessingController.ts
- packages/lms-common/src/index.ts
- packages/lms-common/src/promisifyAbortSignal.ts
- packages/lms-external-backend-interfaces/src/pluginsBackendInterface.ts
- packages/lms-shared-types/src/index.ts
- packages/lms-shared-types/src/llm/processing/GeneratorUpdate.ts
- packages/lms-shared-types/src/llm/processing/ProcessingRequest.ts
- packages/lms-shared-types/src/llm/processing/ProcessingUpdate.ts
Adds the ability for processors to make requests (i.e. asking user to make an input)
> Processing requests init

- packages/lms-client/src/llm/LLMDynamicHandle.ts
- packages/lms-shared-types/src/llm/LLMToolUseSetting.ts
To support:
https://platform.openai.com/docs/guides/function-calling?api-mode=responses#tool-choice
> Add force option to tools

- packages/lms-shared-types/src/ArtifactManifestBase.ts
- packages/lms-shared-types/src/VirtualModelDefinition.ts
Requires https://github.com/lmstudio-ai/lms/pull/219
> Get rid of description in artifacts

- packages/lms-client/src/repository/RepositoryNamespace.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
Depends on https://github.com/lmstudio-ai/lms/pull/229
> lms push takes description

- packages/lms-client/src/repository/RepositoryNamespace.ts
- packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts
Depends on https://github.com/lmstudio-ai/lms/pull/231
> Added a way to login with preauthenticated keys to lms login

- package-lock.json
- packages/lms-communication-client/package.json
- packages/lms-communication-server/package.json
- packages/lms-communication-server/src/AuthenticatedIpcServer.ts
- packages/lms-communication-server/src/IpcServer.ts
- packages/lms-communication-server/src/IpcServerTransport.ts
- packages/lms-communication-server/src/electronTypes.ts
We only use electron for types. Too heavy to pull it.
> Get rid of electron dependency

- packages/lms-client/src/files/FilesNamespace.ts
- packages/lms-client/src/files/ParseDocumentOpts.ts
- packages/lms-client/src/files/ParseDocumentResult.ts
- packages/lms-external-backend-interfaces/src/filesBackendInterface.ts
Adds an endpoint to allow requesting LM Studio to parse a document (still highly experimental).
> Document parsing fuctionality

- packages/lms-client/src/plugins/PluginsNamespace.ts
- packages/lms-client/src/plugins/processing/ProcessingController.ts
- packages/lms-client/src/plugins/processing/ToolsProviderController.ts
- packages/lms-external-backend-interfaces/src/pluginsBackendInterface.ts
Add a method to ctl to get the working directories, which should be used to place extra generated files.
> Add a method to get working directories

- packages/lms-client/src/files/FilesNamespace.ts
- packages/lms-client/src/llm/LLMDynamicHandle.ts
- packages/lms-client/src/llm/LLMGeneratorHandle.ts
- packages/lms-client/src/llm/act.ts
- packages/lms-client/src/modelShared/ModelNamespace.ts
- packages/lms-client/src/repository/ArtifactDownloadPlanner.ts
Make sure to handle the case where the abort signal is already aborted before getting passed in
> Fix abort not working when the abort signal is already aborted prior to being passed in

- publish/cli/make-bin-linux.sh
> Infer ARM URL in linux build
