lmstudio-ai/lmstudio-js

publish/cli/make-bin-win32.sh
Will now get this output on fail:
```
Error: Failed to sign the binary at './dist/lms.exe' with output: 
Command :
<command>
Error :
<error info>
signCommand command for file ./dist/lms.exe FAILED
Signing FAILED
npm ERR! ...
```
This output on success:
```
Attempting to sign './dist/lms.exe'...
Signing was SUCCESSFUL
```
Instead of what was previously a "silent" failure that wouldn't cause an npm ERR
=> Fail make script build if signing is ON, but fails

publish/cli/make-bin-win32.ps1
This was an artifact of the deprecated bash script that does not work in powershell.
=> Fix signtool remove command invocation (//s to /s)

publish/cli/make-bin-win32.ps1
Brings to parity with expectations of deprecated bash command
=> Map both x86 and x64 architecture to node x64 node download

publish/cli/make-bin-win32.ps1
Fix to `make-bin-win32.ps1` so that it can successfully read a `.env` file of the format:
```
ENV_VAR1='value1'
ENV_VAR2='value2'
```
This was the previous, working behavior of the `make-bin-win32.sh` file, but broke when migrated to powershell in https://github.com/lmstudio-ai/lmstudio.js/commit/e4461436be0a0c1f9e9584d7dd46d45d4bf60f8f
=> Fix powershell reading of .env file to specify code-signing environment variables

packages/lms-shared-types/src/index.ts, packages/lms-shared-types/src/retrieval/Chunk.ts, packages/lms-shared-types/src/retrieval/ProcessingStep.ts, packages/lms-shared-types/src/retrieval/RetrievalConfig.ts
Adds `Chunk`, `RetrievalConfig`, and `ProcessingStep` types to `lms-shared-types` for the retrieval API. Linter also appeared to go ham on `index.ts`.
=> Export retrieval API types

packages/lms-common/src/OWLSignal.ts
The direction of the logic is wrong. It should pull on stale, not vice-versa.
=> Pull on stale

packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-client/src/retrieval/RetrievalOpts.ts, packages/lms-external-backend-interfaces/src/llmBackendInterface.ts, packages/lms-kv-config/src/KVConfig.ts, packages/lms-shared-types/src/KVConfig.ts, packages/lms-shared-types/src/retrieval/RetrievalChunkingMethod.ts
Makes server config no longer use instance layer. Instead it uses a dedicated server session layer.
=> Separate out server session config

packages/lms-kv-config/src/schema.ts
Allows the number of threads allocated in the llama.cpp engine threadpool at load time to be set as a config parameter
A part of the fix for:
- https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/130
=> Add cpuThreadPoolSize to llm.load.llama config schematics

packages/lms-shared-types/src/llm/LLMPromptTemplate.ts
Documents the previously ambiguous `LLMJinjaInputFormat`, providing examples of the exact format represented by each
=> Add documentation for LLMJinjaInputFormat

packages/lms-shared-types/src/llm/LLMPromptTemplate.ts
Supercedes https://github.com/lmstudio-ai/lmstudio.js/pull/112
Adds the required `LLMJinjaInputFormat` for Mistral tool-enabled models like https://huggingface.co/bartowski/Ministral-8B-Instruct-2410-GGUF amd https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407. Called `mistralTools`.
Also adds the required `LLMJinjaInputFormat` for Qwen tool-enabled models like https://huggingface.co/lmstudio-community/Qwen2.5-7B-Instruct-GGUF. Called `qwenTools`.
Also adds documentation and cleans up a bit of documentation for `llamaCustomTools`.
=> Add mistralTools, qwenTools LLMJinjaInputFormats

packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-client/src/llm/OngoingPrediction.ts, packages/lms-client/src/plugins/processing/ProcessingController.ts, packages/lms-external-backend-interfaces/src/llmBackendInterface.ts, packages/lms-shared-types/src/index.ts, packages/lms-shared-types/src/llm/LLMPredictionFragment.ts
Changes type of fragment to an object with a single field "content". This breaks backwards compatibility.
=> Fragment is object

packages/lms-shared-types/src/llm/LLMToolUseSetting.ts
Makes the description field of a function in `tools` optional, matching OpenAI's API
=> [LLMTool] Make function description optional

packages/lms-client/src/retrieval/RetrievalOpts.ts, packages/lms-communication/src/Transport.ts, packages/lms-external-backend-interfaces/src/filesBackendInterface.ts, packages/lms-external-backend-interfaces/src/llmBackendInterface.ts, packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts, packages/lms-external-backend-interfaces/src/retrievalBackendInterface.ts, packages/lms-shared-types/src/ChatHistoryData.ts, packages/lms-shared-types/src/CitationSource.ts, packages/lms-shared-types/src/DownloadedModel.ts, packages/lms-shared-types/src/GenericErrorDisplayData.ts, packages/lms-shared-types/src/PluginManifest.ts, packages/lms-shared-types/src/Runtime.ts, packages/lms-shared-types/src/llm/LLMPredictionStats.ts, packages/lms-shared-types/src/llm/processing/ProcessingUpdate.ts, packages/lms-shared-types/src/repository/DownloadProgressUpdate.ts, packages/lms-shared-types/src/retrieval/InternalRetrievalResult.ts, packages/lms-shared-types/src/retrieval/RetrievalChunkingMethod.ts
PR is based on reviewing all the `z.number()` schema entries and looking for those which are not already marked as integers and are one of the following:
* operation or entity IDs
* byte/token/model counts
* array indices
* revision numbers
* page or line numbers
* indentation level counts
=> Mark more integer API schema fields as integers

packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-shared-types/src/llm/LLMPromptTemplate.ts
`inputConfig` becomes required, since it is needed to go from `ChatHistoryData` -> input to the jinja render function
=> [LLMJinjaPromptTemplate] templateHasTools -> useTools, make inputConfig required

packages/lms-kv-config/src/KVConfig.ts, packages/lms-kv-config/src/schema.test.ts, packages/lms-kv-config/src/schema.ts, packages/lms-shared-types/src/SerializedKVConfigSchematics.ts
Before, `KVConfigSchematics` are just implemented as a `baseKey` + a list of allowed keys. For example, a `KVConfigSchematics` can have `baseKey = llm.prediction`, and have allowed keys being `temperature`. Thus accessing `temperature` will result in accessing `llm.prediction.temperature`.
However, this prevents us from unioning two `KVConfigSchematics` that have different base keys (meaning scoped at different levels).
This PR changes the approach into having an aliasing map. For the previous case, we will alias `temperature` to `llm.prediction.temperature`. This greatly increases the versatility of the `KVConfigSchematics`. For example, a `llmPrediction` schematics can include fields from the root level. We can even create alias. Reality can be whatever we want.
This _hopefully_ …
=> Allow KVConfigSchematics to union across schematics that are scoped at different levels.

packages/lms-client/src/embedding/EmbeddingNamespace.ts, packages/lms-client/src/llm/LLMNamespace.ts, packages/lms-kv-config/src/schema.ts, packages/lms-kv-config/src/valueTypes.ts, packages/lms-shared-types/src/index.ts, packages/lms-shared-types/src/llm/LLMLoadModelConfig.ts, publish/sdk/src/exportedTypes.ts
Adds the splitMode parameter to `LLMLlamaAccelerationSetting`.
Follows: https://github.com/ggerganov/llama.cpp/blob/f11cfdfd7fe29436fce512d934c2ff6b94bd89d2/include/llama.h#L210
=> [LLMLlamaAccelerationSetting] Add splitMode param

packages/lms-kv-config/src/KVConfig.ts, packages/lms-kv-config/src/schema.ts, packages/lms-kv-config/src/valueTypes.ts, packages/lms-shared-types/src/KVConfig.ts
Moves draft model to load parameters, removes 'speculative decoder enabled' field, adds a not equals comparison for dependencies (not used yet)
=> Speculative Decoding changes

packages/lms-communication/src/Transport.ts, packages/lms-shared-types/src/Error.ts, packages/lms-shared-types/src/GenericErrorDisplayData.ts, packages/lms-shared-types/src/index.ts, packages/lms-shared-types/src/llm/LLMErrorDisplayData.ts
The new error type will carry information about the engine not supporting a specific feature.
=> Add an error type for engine lacking required feature

packages/lms-kv-config/src/conversion/llmPredictionConfig.ts, packages/lms-kv-config/src/schema.ts, packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
We previously had the limitation that reasoning parsing start/end tags must be a single token. No longer!
=> reasoning start and end can be string now

packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
Hopefully fix the issue "Type instantiation is excessively deep and possibly infinite" when multiple zod versions exist.
=> Fix zod type resolution bug

packages/lms-client/src/llm/tool.ts
https://github.com/lmstudio-ai/lmstudio-js/pull/245, but for `tool`
=> Fix zod schema issue with tool

packages/lms-shared-types/src/embedding/EmbeddingLoadModelConfig.ts, packages/lms-shared-types/src/llm/LLMLoadModelConfig.ts
It was working because of another bug: https://github.com/lmstudio-ai/lmstudio-js/pull/257
=> Fix gpu related settings schema desync from ts types

packages/lms-client/src/embedding/EmbeddingNamespace.ts, packages/lms-client/src/llm/LLMNamespace.ts, packages/lms-kv-config/src/schema.ts, packages/lms-kv-config/src/valueTypes.ts, packages/lms-shared-types/src/GPUSplitStrategy.ts, packages/lms-shared-types/src/index.ts
Creates a new composite value type that called `GPUSplitConfig` that contains:
1. `strategy` - A split strategy enum `evenly` or `priorityOrder`
2. `disabledGpus` - array of gpu indices to disable
3. `priority` - array of gpu indices in priority order
This will be the future of setting how to split models between multiple gpus.
To not make a breaking change, in the API we still use `GPUSetting`, and just convert `GPUSetting` to this new `GPUSplitConfig` when converting it to KV.
Removes `mainGpu` from KV, as this will be set by `priority`
=> GPUSplitConfig

packages/lms-shared-types/src/GPUSplitStrategy.ts
Essentially synonymous to tensor_split as exposed by llama.cpp, high granularity split strategy option.
=> Add custom ratio to GPUSplitStrategy

packages/lms-client/src/friendlyErrorDeserializer.ts, packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-common/src/makePrettyError.ts, packages/lms-external-backend-interfaces/src/llmBackendInterface.ts, packages/lms-shared-types/src/GenericErrorDisplayData.ts, packages/lms-shared-types/src/KVConfig.ts, packages/lms-shared-types/src/llm/LLMPredictionConfig.ts
Allow specifying presets in SDK for .respond, .complete, and .act.
Unfortunately no test coverage at the moment due to no easy way to make sure testing environment having the desired preset.
=> Specifying presets in SDK

packages/lms-common/src/StreamablePromise.ts
The previous logic stops the iteration as soon as the prediction ends. However, there might still be fragments in the buffer that has not been read yet. This makes sure that the iterator finishes the buffer.
=> Fix generation finish earlier than intended, cutting off the last couple tokens,

package-lock.json, package.json
stmux does not work on windows arm
This technically breaks the npm start command, but few people are using it. And If you are indeed using it, you can install stmux globally.
=> Remove stmux

packages/lms-kv-config/src/conversion/llmPredictionConfig.ts, packages/lms-kv-config/src/schema.ts
Add back MLX top-k support and address comment https://github.com/lmstudio-ai/lmstudio-js/pull/192#discussion_r2017414072 that got this feature previously reverted
Ref https://github.com/lmstudio-ai/mlx-engine/issues/59
=> [MLX] Add top-k sampling support

packages/lms-kv-config/src/schema.ts, packages/lms-kv-config/src/valueTypes.ts, packages/lms-shared-types/src/llm/LLMLoadModelConfig.ts
For llama.cpp parameter https://github.com/ggml-org/llama.cpp/blob/b34c859146630dff136943abc9852ca173a7c9d6/common/common.h#L332
Allows you to put KV cache in RAM instead of VRAM
=> Add offloadKVCacheToGpu to load parameters

packages/lms-kv-config/src/schema.ts
Since KV cache is very specific to llm
=> Move offloadKVCacheToGpu to llm.load

packages/lms-client/src/plugins/PluginsNamespace.ts, packages/lms-client/src/plugins/processing/ToolsProviderController.ts, packages/lms-shared-types/src/PluginManifest.ts
Adds a new plugin type called mcpBridge, which is used internally to run MCPs as regular plugins.
=> Add mcp bridge plugin type

packages/lms-client/src/llm/LLMDynamicHandle.ts
This makes sure that there will also be a matching `onToolCallRequestEnd` or `onToolCallRequestFailure` for each `onToolCallRequestStart`, even in the case of failure. Thus those hooks alone are enough to synchronize UI.
=> Call the "onToolCallRequestFailure" callback if the model is generating a tool call + the generation failed.

packages/lms-client/src/PluginContext.ts, packages/lms-client/src/plugins/PluginsNamespace.ts, packages/lms-client/src/plugins/processing/GeneratorController.ts, packages/lms-client/src/plugins/processing/ProcessingController.ts, packages/lms-client/src/plugins/processing/ToolsProviderController.ts, packages/lms-es-plugin-runner/src/generateEntryFile.ts, packages/lms-external-backend-interfaces/src/pluginsBackendInterface.ts
Plugins can now supply global config schematics by doing `context.withGlobalConfigSchematics(xxx)` to register global config schematics.
=> Add support for global config

packages/lms-client/src/llm/LLM.act.heavy.test.ts, packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-client/src/llm/act.ts, packages/lms-shared-types/src/llm/processing/ProcessingUpdate.ts
Makes tool execution synchronous by default (i.e. later tool calls will wait for earlier tool calls to finish before continuing). This does not prevent parallel tool calls, only prevents parallel execution of those tool calls. This makes .act more safe when used with tools that have side-effects which cares about timing/ordering.
The old behavior can be opt back in by specifying `allowParallelToolExecution: true`, which will be more efficient if your tools can run for a long time + they are pure/don't care about timing or ordering.
=> Sync tool call execution by default

.gitmodules
`git clone https://github.com/lmstudio-ai/lmstudio-js.git --recursive` in the development instructions was failing because the submodule URL path was incorrect. it seems the repo was renamed but the submodule URL was not updated accordingly.
This PR updates the URL and also switches the URL format to use https instead of ssh since that will work better out of the box for most people who may not have SSH keys setup and since it's not really necessary for public repos anyways
=> Update URL for lms cli git submodule

packages/lms-shared-types/src/llm/LLMApplyPromptTemplateOpts.ts
We will format the prompt with the tool definitions provided. Currently marked as experimental as we might adjust the "LLMTool" type later.
=> Allow "applyPromptTemplate" to specify tools

packages/lms-client/src/LMStudioClient.ts, packages/lms-client/src/files/FilesNamespace.ts, packages/lms-client/src/files/ParseDocumentOpts.ts, packages/lms-client/src/files/ParseDocumentResult.ts, packages/lms-client/src/llm/GeneratorPredictionResult.ts, packages/lms-client/src/llm/LLMGeneratorHandle.ts, packages/lms-client/src/llm/LLMNamespace.ts, packages/lms-client/src/llm/OngoingGeneratorPrediction.ts, packages/lms-client/src/llm/PredictionResult.ts, packages/lms-client/src/llm/act.ts, packages/lms-client/src/llm/tool.ts, packages/lms-client/src/plugins/PluginsNamespace.ts, packages/lms-client/src/plugins/processing/BaseController.ts, packages/lms-client/src/plugins/processing/GeneratorController.ts, packages/lms-client/src/plugins/processing/ProcessingController.ts, packages/lms-client/src/plugins/processing/ToolsProviderController.ts, packages/lms-client/src/repository/ArtifactDownloadPlanner.ts, packages/lms-client/src/repository/RepositoryNamespace.ts, packages/lms-common/src/text.ts, packages/lms-shared-types/src/files/DocumentParsingOpts.ts, packages/lms-shared-types/src/llm/LLMApplyPromptTemplateOpts.ts, packages/lms-shared-types/src/llm/processing/ProcessingRequest.ts, packages/lms-shared-types/src/repository/ArtifactDownloadPlan.ts
We use `@deprecated` and `@experimental` to mark APIs that are not yet stable yet. This PR unifies the language so they can be replaced easily in the future. In addition, prompt all plugins related APIs (expect those of prediction loop handler) to experimental, so they will now show up in auto complete.
=> Unify deprecations and experimental tags

packages/lms-shared-types/src/llm/LLMToolUseSetting.ts
It appears there is no way to create a tool with root level $defs using the TypeScript SDK. Thus tested using the following python MCP:
```py
from mcp.server.fastmcp import FastMCP
from pydantic import BaseModel
mcp = FastMCP("Demo")
class AA(BaseModel):
a: int
@mcp.tool()
def sum(a: AA, b: AA) -> int:
"""Add two numbers"""
return a + b
```
`lmsd log stream` output:
```
input: "<start_of_turn>user
The following tools are available for you to use:
[
{
"type": "function",
"function": {
"name": "sum",
"description": "Add two numbers",
"parameters": {
"type": "object",
"properties": {
"a": {
"$ref": "#/$defs/AA"
},
"b": {
"$ref": "#/$defs/AA"
}
},
"required": [
"a",
"b"
],
"$defs": {
"AA": {
"properties": {
"a": {
"title": "A",
"type": "integer"
}
},
"required": [
"a"
],
"title": "AA", …
```
=> Allow root $defs in tool schema

packages/lms-client/src/index.ts, packages/lms-client/src/llm/LLM.act.heavy.test.ts, packages/lms-client/src/llm/act.ts, packages/lms-client/src/llm/tool.ts, publish/sdk/src/index.ts
Adds support for unimplemented tools (experimental). When an unimplemented tool is passed into .act, upon called, instead of failing, it gracefully terminates .act and return the control back to the user.
=> Unimplemented tool support in .act

packages/lms-communication-client/src/AuthenticatedWsClientTransport.ts, packages/lms-communication-client/src/WsClientTransport.ts
There are cases where we know a connection is broken but not necessarily the TCP stack. (for example, if we run the server in a process that we control and that process is killed)
This PR makes so that it is possible to feed external errors into WSClientTransport, which upon triggered, will poison the transport and gracefully terminate all on going requests.
=> Allow feeding external error into *WSClientTransport

packages/lms-client/src/system/SystemNamespace.ts, packages/lms-external-backend-interfaces/src/systemBackendInterface.ts
This would expose the `lms` client to be able to use stop and start server RPC calls
=> Start and stop server using RPC

packages/lms-client/src/embedding/.test-snapshots/EmbeddingModel.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.act.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.complete.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.respond.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.speculativeDecoding.heavy.test.ts.snap, packages/lms-client/src/llm/.test-snapshots/LLM.vision.heavy.test.ts.snap, packages/lms-client/src/llm/LLM.act.heavy.test.ts, packages/lms-client/src/llm/LLM.complete.heavy.test.ts, packages/lms-client/src/llm/LLM.respond.heavy.test.ts, packages/lms-client/src/llm/LLM.speculativeDecoding.heavy.test.ts, packages/lms-client/src/llm/LLM.vision.heavy.test.ts
We added new fields such as `quantization` and `isStructural`. Added them to the heavy tests.
(heavy tests are still kinda flaky as it is hardware/engine dependent. We should eventually improve them, but just fix the snapshots for now so it doesn't block release.)
=> Update heavy tests to contain new fields

package.json
Clean the `.turbo` directory when executing `npm run clean`.
=> Clean .turbo directory

packages/lms-client/src/llm/act.ts
`onMessage` is currently being called with a tool result message that looks like:
```
{"role":"tool","content":[{"type":"toolCallResult","content":"undefined","toolCallId":"162305404"}
```
for unimplemented tools.
We shouldn't be returning any tool results for unimplemented tools. Fix this by moving the result handling to only happen if the `tool.implementation` and other logic after implementation is called doesn't throw.
=> [.act] Don't append tool call result for unimplemented tool

packages/lms-kv-config/src/KVConfig.ts, packages/lms-kv-config/src/index.ts, packages/lms-kv-config/src/schema.ts
Adds a helper method for `KVConfigBuilder` to provide extension prefixed fields and have a `customFieldConfigSchematics`
=> Custom field schematics and builder

packages/lms-client/src/embedding/EmbeddingDynamicHandle.ts, packages/lms-client/src/llm/LLMDynamicHandle.ts, packages/lms-client/src/modelShared/DynamicHandle.ts, packages/lms-external-backend-interfaces/src/baseModelBackendInterface.ts, packages/lms-kv-config/src/conversion/embeddingLoadModelConfig.ts, packages/lms-kv-config/src/conversion/llmLoadModelConfig.ts, packages/lms-kv-config/src/conversion/llmPredictionConfig.ts, packages/lms-kv-config/src/index.ts, packages/lms-kv-config/src/schema.ts, packages/lms-shared-types/src/GPUSplitStrategy.ts, packages/lms-shared-types/src/index.ts
Adds the ability to get configurations programmatically via the SDK. 
For LLMs:
```typescript
const predictionConfig = await llm.getBasePredictionConfig();
const loadConfig = await llm.getLoadConfig();
```
and for embedding models:
```typescript
const loadConfig = await embedding.getLoadConfig();
```
=> Add ability to fetch load and prediction configs

packages/lms-shared-types/src/GPUSplitStrategy.ts
Previously, if SDK did not specify gpu settings, we still added an override with default values. Instead, if gpuSettings is undefined, don't override.
Fixes https://github.com/lmstudio-ai/lms/issues/338
=> Don't override GPU settings if gpu settings are not overidden

packages/lms-client/src/repository/ArtifactDownloadPlanner.ts, packages/lms-client/src/repository/ModelSearchResultDownloadOption.ts, packages/lms-client/src/repository/RepositoryNamespace.ts, packages/lms-external-backend-interfaces/src/repositoryBackendInterface.ts, packages/lms-shared-types/src/repository/ModelSearch.ts
This PR plans to fix the artifact download planner clean up, splitting the abort events into two types - `cancelPlan` and `cancelDownload` which will resolve a lot of communication warnings. 
This PR also brings in `compatibilityType` for Model search option data
=> Disposing planner should not cancel download
